### PR TITLE
add assignee to issues

### PR DESCRIPTION
**Pull request by tdivoll**
This PR is to add an assignee to issues when websites are down. For now, I put my own user as a test. Ideally, emails would go to ccv-bot and then if possible, ccv-bot could send notifications to a Slack channel.

### CODE REVIEW

**Comment by tdivoll** [comment]
@broarr The GH issues that are created when a website is down go to different repos. Here's the one from the most recent outage of `pricaimcit`: https://github.com/brown-ccv/check-website-up/issues?q=is%3Aissue+is%3Aclosed

**Review by broarr — APPROVED** [review]

**Comment by broarr** [comment]
This looks good to me. I'm doing some research into slack integration with github actions too

https://github.com/slackapi/slack-github-action

This looks promising. I'll take a peek and see how it works at some point

**Comment by broarr** [comment]
#51

**Review by kmilo9999 — APPROVED** [review]
I recommend you to test it first to see if you get emails once the issue is assigned.

**Pull request merged**
